for _ in range(int(input())):
    r, c = map(int, input().split())
    if( r == c == 1):
        print("18")
        print("8 8")
        print("7 7")
        print("8 6")
        print("6 8")
        print("5 7")
        print("8 4")
        print("4 8")
        print("3 7")
        print("8 2")
        print("2 8")
        print("1 7")
        print("7 1")
        print("6 2")
        print("5 1")
        print("1 5")
        print("2 4")
        print("1 3")
        print("3 1")
    elif( r == c):
        print("19")
        print("1 1")
        print("8 8")
        print("7 7")
        print("8 6")
        print("6 8")
        print("5 7")
        print("8 4")
        print("4 8")
        print("3 7")
        print("8 2")
        print("2 8")
        print("1 7")
        print("7 1")
        print("6 2")
        print("5 1")
        print("1 5")
        print("2 4")
        print("1 3")
        print("3 1")